# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1f7718288438eb60b25415713f6735cbf6e6c9e79b3d7930f077f8e4f93af66a40d581430406cccf5ec51b1dd0d1594c16d783ebc9107188647528d23998b80

test:
  secret_key_base: 652ebae92185c54efe71ad0f0fd9a873363790907c69e308f16ecccb1946ab8660a6461a7d39719df2c1a4f886f7a2e33c568ff1a808319ca8e9b2ed3008eb28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
